import type {
  DeviceModel,
  PricingPolicy,
  PrivateProduct,
  StoreSettings,
} from "./types";
export const artwork = {
  phone: "/showcase/sailan-showcase-phones.png",
  laptop: "/showcase/sailan-showcase-laptop.png",
  gaming: "/showcase/sailan-showcase-controller.png",
  logo: "/brand/sailan-official.png",
};
const rows = [
  [
    "iphone-16-pro-256gb-unlocked",
    "iPhone 16 Pro",
    "Apple",
    "Phones",
    "Excellent",
    "256GB",
    "",
    "A18 Pro",
    "",
    "Unlocked",
    "Natural Titanium",
    69900,
    3,
    "phone",
  ],
  [
    "iphone-15-pro-max-256gb-unlocked",
    "iPhone 15 Pro Max",
    "Apple",
    "Phones",
    "Good",
    "256GB",
    "",
    "A17 Pro",
    "",
    "Unlocked",
    "Natural Titanium",
    57900,
    2,
    "phone",
  ],
  [
    "iphone-15-pro-max-512gb-unlocked",
    "iPhone 15 Pro Max",
    "Apple",
    "Phones",
    "Excellent",
    "512GB",
    "",
    "A17 Pro",
    "",
    "Unlocked",
    "Black Titanium",
    66900,
    1,
    "phone",
  ],
  [
    "macbook-air-m3-13",
    "MacBook Air 13-inch",
    "Apple",
    "MacBooks",
    "Excellent",
    "256GB",
    "16GB",
    "Apple M3",
    "Integrated",
    "",
    "Silver",
    74900,
    2,
    "laptop",
  ],
  [
    "macbook-pro-m3-14",
    "MacBook Pro 14-inch",
    "Apple",
    "MacBooks",
    "Open Box",
    "512GB",
    "18GB",
    "Apple M3 Pro",
    "Integrated",
    "",
    "Space Black",
    124900,
    1,
    "laptop",
  ],
  [
    "dell-latitude-5540",
    "Dell Latitude 5540",
    "Dell",
    "Laptops",
    "Good",
    "512GB",
    "16GB",
    "Intel Core i5",
    "Integrated",
    "",
    "Gray",
    41900,
    4,
    "laptop",
  ],
  [
    "dual-sense-controller",
    "Wireless Gaming Controller",
    "Sony",
    "Accessories",
    "Open Box",
    "Not applicable",
    "",
    "",
    "",
    "",
    "White",
    4900,
    3,
    "gaming",
  ],
  [
    "playstation-5-disc",
    "PlayStation 5 Disc Edition",
    "Sony",
    "Gaming",
    "Excellent",
    "1TB",
    "",
    "",
    "",
    "",
    "White",
    34900,
    2,
    "gaming",
  ],
  [
    "iphone-14-screen-repair",
    "iPhone 14 · Cracked Screen",
    "Apple",
    "Repair Devices",
    "Repair / Parts",
    "128GB",
    "",
    "A15 Bionic",
    "",
    "Unlocked",
    "Midnight",
    15900,
    1,
    "phone",
  ],
  [
    "sailan-performance-pc",
    "Sailan Performance PC",
    "Custom PC",
    "Desktops",
    "Brand New",
    "1TB",
    "32GB",
    "AMD Ryzen 7",
    "NVIDIA RTX 4070",
    "",
    "Black",
    119900,
    1,
    "logo",
  ],
];
export const sampleProducts: PrivateProduct[] = rows.map((r, i) => ({
  revision: 0,
  id: `sample-${i + 1}`,
  slug: String(r[0]),
  sku: `ST-DEMO-${String(i + 1).padStart(3, "0")}`,
  title: String(r[1]),
  brand: String(r[2]),
  model: String(r[1]),
  category: String(r[3]),
  condition: String(r[4]),
  storage: String(r[5]),
  ram: String(r[6]),
  cpu: String(r[7]),
  gpu: String(r[8]),
  carrier: String(r[9]),
  color: String(r[10]),
  price: Number(r[11]),
  quantity: Number(r[12]),
  images: [artwork[r[13] as keyof typeof artwork]],
  batteryHealth: "See inspection report before purchase",
  status: "Available",
  description:
    "A sample listing showing how Sailan Tech devices will be presented. Specifications and price are examples; the image is illustrative. This item is not available for purchase.",
  specifications: {
    Storage: String(r[5]),
    Processor: String(r[7]),
    Color: String(r[10]),
  },
  included: ["Inclusions confirmed on the final inventory listing"],
  featured: i < 6,
  sample: true,
  discount: i === 1 ? 4000 : 0,
  soldCount: 0,
  createdAt: "2026-09-26T12:00:00.000Z",
  cost: 0,
  supplier: "",
  purchaseDate: "",
  imei: "",
  serial: "",
  weight: "",
}));
const deviceRows: [string, string, string, number, string[]][] = [
  ["iPhone", "Apple", "iPhone 16 Pro Max", 62000, ["256GB", "512GB", "1TB"]],
  [
    "iPhone",
    "Apple",
    "iPhone 16 Pro",
    53000,
    ["128GB", "256GB", "512GB", "1TB"],
  ],
  ["iPhone", "Apple", "iPhone 16", 40000, ["128GB", "256GB", "512GB"]],
  ["iPhone", "Apple", "iPhone 15 Pro Max", 52000, ["256GB", "512GB", "1TB"]],
  [
    "iPhone",
    "Apple",
    "iPhone 15 Pro",
    39000,
    ["128GB", "256GB", "512GB", "1TB"],
  ],
  ["iPhone", "Apple", "iPhone 15", 28000, ["128GB", "256GB", "512GB"]],
  ["iPhone", "Apple", "iPhone 14", 19000, ["128GB", "256GB", "512GB"]],
  ["Samsung", "Samsung", "Galaxy S24 Ultra", 40000, ["256GB", "512GB", "1TB"]],
  ["Samsung", "Samsung", "Galaxy S23", 19000, ["128GB", "256GB"]],
  ["Other Phone", "Google", "Pixel 9", 22000, ["128GB", "256GB"]],
  ["iPad", "Apple", "iPad Pro M4", 50000, ["256GB", "512GB", "1TB", "2TB"]],
  ["iPad", "Apple", "iPad 10th generation", 14000, ["64GB", "256GB"]],
  ["Tablet", "Samsung", "Galaxy Tab S9", 22000, ["128GB", "256GB"]],
  [
    "MacBook",
    "Apple",
    "MacBook Air M3",
    49000,
    ["256GB", "512GB", "1TB", "2TB"],
  ],
  ["MacBook", "Apple", "MacBook Pro M3 Pro", 75000, ["512GB", "1TB", "2TB"]],
  ["Laptop", "Dell", "Latitude 5540", 23000, ["256GB", "512GB", "1TB"]],
  ["Laptop", "Lenovo", "ThinkPad T14", 24000, ["256GB", "512GB", "1TB"]],
  ["Laptop", "HP", "EliteBook 840", 21000, ["256GB", "512GB", "1TB"]],
  ["Laptop", "ASUS", "ROG Zephyrus", 50000, ["512GB", "1TB", "2TB"]],
  ["Laptop", "Acer", "Aspire 5", 15000, ["256GB", "512GB", "1TB"]],
  ["Laptop", "Microsoft", "Surface Laptop 5", 25000, ["256GB", "512GB", "1TB"]],
  ["Desktop", "Dell", "OptiPlex 7000", 23000, ["256GB", "512GB", "1TB"]],
  [
    "Gaming PC",
    "Custom PC",
    "Custom gaming desktop",
    35000,
    ["512GB", "1TB", "2TB"],
  ],
  ["PlayStation", "Sony", "PlayStation 5", 24000, ["825GB", "1TB"]],
  ["Xbox", "Microsoft", "Xbox Series X", 22000, ["1TB", "2TB"]],
  ["Nintendo", "Nintendo", "Nintendo Switch OLED", 13000, ["64GB"]],
  ["Apple Watch", "Apple", "Apple Watch Series 9", 13000, ["Not applicable"]],
  ["Smartwatch", "Samsung", "Galaxy Watch 6", 7000, ["Not applicable"]],
];
export const sampleDevices: DeviceModel[] = deviceRows.map(
  ([category, brand, name, base, storage]) => ({
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    category,
    brand,
    name,
    base,
    storage,
    enabled: true,
    ...(["MacBook", "Laptop", "Desktop", "Gaming PC"].includes(category)
      ? {
          configurations: {
            cpu: ["Standard configuration"],
            ram: [name === "MacBook Pro M3 Pro" ? "18GB" : "16GB"],
            gpu: ["Integrated"],
          },
        }
      : {}),
  }),
);
export const defaultPolicy: PricingPolicy = {
  multipliers: { None: 1, Light: 0.9, Moderate: 0.75, Heavy: 0.6 },
  deductions: {
    "Small crack": 7000,
    "Major crack": 12000,
    "Screen does not work": 15000,
    touch: 4000,
    biometrics: 6000,
    back: 4500,
    battery: 3500,
    carrier: 4000,
  },
  accessories: {
    "Original box": 500,
    "Charging cable": 500,
    "Power adapter": 1000,
    Controller: 1500,
    Keyboard: 1000,
  },
  storage: {
    "64GB": 0,
    "128GB": 0,
    "256GB": 0,
    "512GB": 4000,
    "825GB": 0,
    "1TB": 7000,
    "2TB": 12000,
    "Not applicable": 0,
  },
  ram: {
    "8GB": 0,
    "16GB": 2000,
    "18GB": 3000,
    "24GB": 4000,
    "32GB": 5000,
    "64GB": 9000,
  },
  cpu: {
    "Standard configuration": 0,
    "Intel Core i5": 0,
    "Intel Core i7": 3000,
    "Intel Core i9": 6000,
    "AMD Ryzen 5": 0,
    "AMD Ryzen 7": 3000,
    "AMD Ryzen 9": 6000,
    "Apple silicon": 0,
  },
  gpu: {
    Integrated: 0,
    "NVIDIA RTX 3060": 7000,
    "NVIDIA RTX 4060": 10000,
    "NVIDIA RTX 4070": 18000,
    "AMD Radeon": 8000,
  },
  partsMultiplier: 0.2,
  maxOffer: 200000,
  minMargin: 5000,
  feesPercent: 12,
  shipping: 1500,
  approved: false,
};
export const defaultSettings: StoreSettings = {
  live: false,
  shippingCents: 1500,
  shippingText:
    "Shipping options and dispatch estimates will be shown when live inventory is available.",
  returnsText:
    "Returns terms will be published before purchasing is enabled. Contact support with questions about a specific device.",
  warrantyText:
    "Warranty coverage will be stated on each live device listing. No coverage is promised for sample listings.",
  inspectionText:
    "We inspect the device and confirm the final offer. If its condition differs, you can accept or decline a revised offer before payout.",
  dropoffInstructions:
    "Wait for Sailan Tech to confirm your appointment and drop-off address. Do not visit an unconfirmed address.",
  shipInstructions:
    "Wait for confirmed shipping instructions before sending your device. Back up your data, remove personal accounts and locks, and erase the device before shipping.",
  supportEmail: "",
  privacyText: "",
  termsText: "",
};
export function publicProduct(product: PrivateProduct) {
  const { cost, supplier, purchaseDate, imei, serial, weight, ...safe } =
    product;
  void cost;
  void supplier;
  void purchaseDate;
  void imei;
  void serial;
  void weight;
  return safe;
}
